#╔═════════════════════════╗╔════════════════════════════════════╗╔═════════════════════════╗
#║   Наш телеграм канал    ║║      Наше сообщество вконтакте     ║║  Наш дискорд сервер     ║
#║   t.me/spacestudiomc    ║║       vk.com/spacestudiomine       ║║   dsc.gg/spacestudiomc  ║
#╚═════════════════════════╝╚════════════════════════════════════╝╚═════════════════════════╝
#╔═════════════════════════════════════════════════════════════════════════════════════════════╗
#║  ███████╗██████╗  █████╗  ██████╗███████╗    ███████╗████████╗██╗   ██╗██████╗ ██╗ ██████╗  ║
#║  ██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝    ██╔════╝╚══██╔══╝██║   ██║██╔══██╗██║██╔═══██╗ ║
#║  ███████╗██████╔╝███████║██║     █████╗      ███████╗   ██║   ██║   ██║██║  ██║██║██║   ██║ ║
#║  ╚════██║██╔═══╝ ██╔══██║██║     ██╔══╝      ╚════██║   ██║   ██║   ██║██║  ██║██║██║   ██║ ║
#║  ███████║██║     ██║  ██║╚██████╗███████╗    ███████║   ██║   ╚██████╔╝██████╔╝██║╚██████╔╝ ║
#║  ╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝╚══════╝    ╚══════╝   ╚═╝    ╚═════╝ ╚═════╝ ╚═╝ ╚═════╝  ║
#╚═════════════════════════════════════════════════════════════════════════════════════════════╝
#
#                               ╔════════════════════════════════════╗
#                               ║         Кодер - m0onmag            ║
#                               ║         t.me/m0onmag               ║
#                               ╚════════════════════════════════════╝

name: SpaceChest
version: '1.0'
main: ru.moonmag.SpaceChest
api-version: '1.16'
author: [ SpaceDev ]
softdepend:
  - DecentHolograms
commands:
  spacechest:
    permission: spacechest.use

permissions:
  spacechest.use:
   default: op